general {
    # Prevent the lock screen from being bypassed with Ctrl+Alt+Backspace
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
    brightness = 0.8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(89b4faee)
    inner_color = rgba(1e1e2eee)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <i>Enter password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(cdd6f4ee)
    font_size = 64
    font_family = Sans
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(cdd6f4ee)
    font_size = 18
    font_family = Sans
    position = 0, 10
    halign = center
    valign = center
}

